package com.uipro.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ContactUsDesign extends VerticalLayout {
	protected TextField firstName;
	protected TextField lastName;
	protected TextField jobTitle;
	protected TextField phoneNumber;
	protected TextField email;
	protected TextField company;
	protected TextField url;
	protected TextArea notes;
	protected Button send;
	protected Button cancel;

	public ContactUsDesign() {
		Design.read(this);
	}
}
