package com.uipro.views;

import com.uipro.entity.UserProfile;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserProfileDesign extends CssLayout {
	protected TextField firstName;
	protected TextField lastName;
	protected HorizontalLayout dateOfBirthWrapper;
	protected TextField month;
	protected TextField day;
	protected TextField year;
	protected ComboBox language;
	protected Button add;
	protected CssLayout phoneNumberWrapper;
	protected TextField countryCode;
	protected TextField phoneNumber;
	protected TextField email;
	protected Button submit;
	protected Button cancel;

	public UserProfileDesign() {
		Design.read(this);
		monitorProfileChanges();
	}
	
	public void monitorProfileChanges() {
		submit.addClickListener(new Button.ClickListener() {			
			@Override
			public void buttonClick(ClickEvent event) {
				System.out.println("Button has been clicked to save the profile.");
				UserProfile profile = getUserDataFromProfile();
				profile.toString();
			}
		});
	}
	

	private UserProfile getUserDataFromProfile() {
		String fn = firstName.getValue();
		String ln = lastName.getValue();
		
		String emailId = email.getValue();
		
		String cc = countryCode.getValue();
		String ph = phoneNumber.getValue();
		String phoneNumber = cc + "-" + ph;
		
		String mm = month.getValue();
		String dd = day.getValue();
		String yy = year.getValue();
		String dob = dd + "/" + mm + "/" + yy;
		
		UserProfile profile = new UserProfile(fn, ln, emailId, phoneNumber, dob);
		
		return profile;
	}
}
