package com.uipro.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserProfileDesign extends CssLayout {
	protected TextField firstName;
	protected TextField lastName;
	protected HorizontalLayout dateOfBirthWrapper;
	protected TextField month;
	protected TextField day;
	protected TextField year;
	protected CssLayout phoneNumberWrapper;
	protected TextField countryCode;
	protected TextField phoneNumber;
	protected TextField email;
	protected Button submit;
	protected Button cancel;

	public UserProfileDesign() {
		Design.read(this);
	}
}
